CREATE TABLE user_base (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(45) NOT NULL,
  gender VARCHAR(3) NOT NULL,
  age INTEGER NOT NULL,
  address VARCHAR(100) NOT NULL,
  lvl INTEGER NOT NULL
)

CREATE TABLE user_order (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  item_name VARCHAR(45) NOT NULL,
  amount INTEGER NOT NULL,
  total_price NUMERIC(12,2) NOT NULL
)
