package xyz.calvinwilliams.sqlaction;

public enum SqlActionPredicateEnum {
	SQLACTION_PREDICATE_NONE ,
	SQLACTION_PREDICATE_SELECT ,
	SQLACTION_PREDICATE_INSERT ,
	SQLACTION_PREDICATE_UPDATE ,
	SQLACTION_PREDICATE_DELETE
}
